server:
  port: 9527

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP

zuul:
  routes:
    mydept.serviceId: springcloud-dep
    mydept.path: /mydep/**
  prefix: /joe
#  ignored-services: springcloud-dep #原真实服务名忽略
  ignored-services: "*" #忽略多个服务

spring:
  application:
    name: springcloud-9527-zuul-gateway

info:
  app.name: joe-microservicecloud
  company.name: www.joe.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$